ANTsX/ANTs

Examples/ComposeMultiTransform.cxx
`ComposeMultiTransform` always returned 1 which stopped my nipype commandline (No error message was thrown and the result file looks good).
It seems that it always `return EXIT_FAILURE` regardless of the `if( is_parsing_ok )` condition. Could you guys pls double check this fix? Thanks!
=> FIX: ComposeMultiTransform always return 1 when argc > 3

Examples/ImageMath.cxx
I'm going to need this for a new feature in plot.antsImage in ANTsR for checking
registration where overlaying edge-detected image on another image gives a clear feeling of
how registration has worked :
- Leaving thresholds to ITK defaults gives more stable
results.
- We don't need rescaling because the output of the filter is
(on its own) between 0 and 1. 
- Some cleaning up of the code, removing unnecessary variables, `image2`
=> BUG: ImageMath Canny edge detection gives 0 output

Examples/itkantsRegistrationHelper.h, Examples/itkantsRegistrationHelper.hxx
GetShrinkImageOutputInformation provides a consistent way to compute the
outputImage space for each level of a registration in a consistent way.
By always using the same reference image, we can ensure that the same
shrink results always are produced.
=> ENH: Make a member function to simplify use

Examples/CMakeLists.txt
When installing ANTs, target antsUtilities was not installed.
=> ENH: Addition of an install rule for target antsUtilities

Examples/antsRegistration.cxx, Examples/antsRegistrationTemplateHeader.cxx, Examples/antsRegistrationTemplateHeader.h, ImageRegistration/itkANTSImageTransformation.cxx, Utilities/itkantsReadWriteTransform.h
Added support for writing .xfm files to ANTS and  antsRegistration binaries. 
antsRegistration will have --minc option to make it produce .xfm files as output.
=> Add support for writing output in minc-style .xfm  files

Examples/antsRegistrationTemplateHeader.cxx, Examples/antsRegistrationTemplateHeader.h, Utilities/itkantsReadWriteTransform.h
1. Fixed writing transformations per stage in minc-style .xfm files
2. Fixed output in case of unsupported transformation type, fixes stnava/ANTs#207
3. Changed transformation type to DisplacementFieldTransform for all non-linear transforms when writing individually or as composite
=> Fixed writing transformations

SuperBuild.cmake, SuperBuild/External_ITKv4.cmake
Added support for MINC2 in superbuild
=> Add option for MINC2 support to superbuild

Examples/CMakeLists.txt, Scripts/antsJointLabelFusion.sh, Scripts/antsMalfLabeling.sh, Scripts/antsMultivariateTemplateConstruction.sh, Scripts/antsMultivariateTemplateConstruction2.sh, Scripts/buildtemplateparallel.sh, Scripts/waitForSlurmJobs.pl
I've added a `waitForSlurmJobs.pl` script modeled after the similar scripts for SGE, PBS, and XGrid.
I've also enhanced the 5 scripts that support cluster parallelization to also support SLURM:
* `antsJointLabelFusion.sh`
* `antsMalfLabeling.sh`
* `antsMultivariateTemplateConstruction.sh`
* `antsMultivariateTemplateConstruction2.sh`
* `buildtemplateparallel.sh`
Please note that I've only been able to test the `antJointLabelFusion.sh` and `antsMultivariateTemplateConstruction.sh` with real jobs.  I don't use the other scripts and thus don't have complete test cases I can use to verify expected behavior.
I'm happy to restructure my commits and submit separate pull requests for the well-tested and poorly-tested changes, and I'm also happy to go back and perform any stylistic (or other) …
=> Added support for the SLURM cluster resource manager

Examples/DenoiseImage.cxx, Examples/antsJointFusion.cxx, Examples/antsJointTensorFusion.cxx, Temporary/itkMeanSquaresPointSetToPointSetIntensityMetricv4.h, Utilities/itkImageIntensityAndGradientToPointSetFilter.h
When overriding a parent class function from ITK, we need
to use ITK_OVERRIDE to improve long term maintenance challenges
by ensuring that if the parent class API changes, these can be
readily found in the sub-classes.
=> COMP: Add missing ITK_OVERRIDE statements

ExternalApplications/MALF/CMakeLists.txt, ExternalApplications/MALF/README.md
/usr/sbin/sa provided by psacct which is well-known utility and should be renamed.
Reference: https://github.com/stnava/ANTs/issues/242
Signed-off-by: Igor Gnatenko <i.gnatenko.brain@gmail.com>
=> rename 'sa' to 'adaBoostSegmentationRefinement'

Examples/antsMotionCorrDiffusionDirection.cxx
Previously this would only work with affine motion correction input.
Also require a 3D reference image for antsMotionCorrDiffusionDirection. This may be an inconvenience for some users but it is necessary to ensure that the direction matrix is set correctly.
=> ENH: Support correction of diffusion directions when motion correction is rigid

Scripts/antsCorticalThickness.sh
allow stages 1 to 5 to be called separately and in order.  this permits finer grained control over the process timing. produces nearly identical results to and is backward compatible with the unstaged antsCorticalThickness.  the test comparison is based on the ants example for antsCorticalThickness:
#!/bin/bash
DATA_DIR=${PWD}
TEMPLATE_DIR=${DATA_DIR}/Template/
OUT_DIR=${DATA_DIR}/OutputT1Only/
bash ${ANTSPATH}antsCorticalThickness.sh -d 2 -x 25 -u 0 \
-a ${DATA_DIR}/IXI002-Guys-0828-T1_slice90.nii.gz \
-e ${TEMPLATE_DIR}template_slice80.nii.gz \
-m ${TEMPLATE_DIR}template_cerebrum_mask_slice80.nii.gz \
-p ${TEMPLATE_DIR}prior%d_slice80.nii.gz \
-o ${OUT_DIR}example
OUT_DIR=${DATA_DIR}/OutputT1OnlyByStage/
for stage in 1 2 3 4 5 ; do
bash ${ANTSPATH}antsCorticalThickness.sh -d 2 -x 25 -u …
=> ENH: allows ansCorticalThickness to be called via 5 separate stages

Examples/DenoiseImage.cxx, Utilities/ReadWriteData.h, Utilities/itkAdaptiveNonLocalMeansDenoisingImageFilter.h, Utilities/itkAdaptiveNonLocalMeansDenoisingImageFilter.hxx
@ntustison Nick,  The denoising program is very nice, but the output images where on a vastly different range than the input images.  This was pretty easy to remedy by simply applying a linear intensity transfer function such that the intensity rescaled output is most like the input image.
This patch hardcodes to always do the rescaling (a computationally cheap operation).  It should be easy to add a command line option for turning this on/off, but I'm not fluent in the ants command line option behaviors.
=> Normalize denoised image to input range

Scripts/antsLongitudinalCorticalThickness.sh
Changed antsLongitudinalCorticalThickness to allow c=5 (SLURM) to be recognized as a valid parallel control type.
=> Added SLURM as a valid parallel control type in antsLongitudinalCorticalThickness

Scripts/antsMultivariateTemplateConstruction2.sh
Hello,
I think I found and fixed a small bug where the job prefix was not being written out for SGE jobs in the 2nd stage.
I also took the opportunity to change the pattern used to strip file extensions from %.*.* to %%.* - the latter will match against .nii as well as .nii.gz, if anyone wants to change the script to output uncompressed Nifti files.
Thanks,
TOby
=> antsMultivariateTemplateConstruction2 not prefixing SGE jobs correctly

Examples/Atropos.cxx, ImageSegmentation/antsAtroposSegmentationImageFilter.h, ImageSegmentation/antsAtroposSegmentationImageFilter.hxx, ImageSegmentation/itkWeightedVotingFusionImageFilter.h, ImageSegmentation/itkWeightedVotingFusionImageFilter.hxx, Utilities/itkN3MRIBiasFieldCorrectionImageFilter.h, Utilities/itkN3MRIBiasFieldCorrectionImageFilter.hxx
When applying a masking operation, any non-zero value
in the image should be considered foreground.  This is
the behavior of the itkMaskImageFilter, and the
itkSpatialImageMaskObject filters.  This makes using
the same image (even an label map image with multiple
labels) appropriate across different uses (i.e. registration
and segmentation).
In all uses inside ANTs, this had been hard coded to the
forground being equal to a value of 1, and no cases were found
that allowed for changing the mask match value.  For masks that
have only values of zero and 1, backwards compatibility is preserved.
For uses where label maps or intensity images were used, this
changes behavior, but in a way that makes ants tools consistent with
other ITK based behaviors.
=> ENH: Masking operations uniform use nonzero values

Utilities/itkAdaptiveNonLocalMeansDenoisingImageFilter.hxx
Denoise image filter was behaving erratically an that
often caused images with very poor output quality to be produced.
Initializing this variable did not fix the overall problem.
=> BUG: Valgrind detected uninitialized variable

Examples/CMakeLists.txt
Exposing all applications in CMake would be too much considering that there are more
than 80 applications built as part of ANTS. This commit introduces advanced options
that are not visible in CMake's user interface, that allow to pick only the
tools that ones wants to build when BUILD_ALL_ANTS_APPS is set to OFF.
If one wants to build 'StackSlices', they need to pass an extra variable called
ANTS_BUILD_StackSlices to CMake and set it to ON.
e.g: cmake -DANTS_SUPERBUILD:BOOL=OFF -DBUILD_ALL_ANTS_APPS:BOOL=OFF\
-DANTS_BUILD_StackSlices=ON ../ANTs
More generally, one needs to use the variable 'ANTS_BUILD_${ANTS_APP}' to build
${ANTS_APP}.
=> ENH: Allow advanced users to build only necessary applications.

Utilities/ReadWriteData.h
ImageFileWriter offers a SetUseCompression option which turns on compression:
http://www.itk.org/Doxygen/html/classitk_1_1ImageFileWriter.html#a8afafaf0d9fe64cfcbb5100d01509dd4
For writers that support compression this turns it on internally during writing, for those that don't support it, it appears to be a no-op.
This feature is particularly important for the MINC format, which has internal lossless compression. Right now ANTs produces *huge* MINC files because compression is disabled. It does not appear to have an impact on .nii and .nii.gz outputs from my testing.
Questions:
- would you accept changes to all instances of ImageFileWriter in the ANTs codebase? Right now MINC displacement transforms are still uncompressed in this patch
- should this be controllable via a command-line …
=> Work in Progress: Enable compression ImageFileWriter calls

Scripts/antsIntroduction.sh, Scripts/antsJointLabelFusion.sh, Scripts/antsMalfLabeling.sh, Scripts/antsMultivariateTemplateConstruction.sh, Scripts/antsMultivariateTemplateConstruction2.sh, Scripts/antsRegistrationSpaceTime.sh, Scripts/antsRegistrationSyN.sh, Scripts/antsRegistrationSyNQuick.sh, Scripts/buildtemplateparallel.sh
The "cleanup" function in the various bash scripts did something like
```
runningANTSpids=( `ps -C antsRegistration -C ImageMath| awk '{ printf "%s\n", $1 ; }'` )
```
This does a system-wide trawl of the matching commands (varies by script), including all users. It's unlikely that you could kill other people's jobs unless you're root, but you can kill jobs of your own that are unrelated to the script you're trying to stop. 
I replaced this line with
```
runningANTSpids=$( ps --ppid $$ -o pid= )
```
which attempts to kill off child processes of the script. This includes the ps command itself, which will always finish before it can be killed, but it won't affect programs not launched from the script.
=> BUG: cleanup function in bash scripts killed all matching processes

SuperBuild/External_ITKv4.cmake
ITK.org is 4-5x slower than github (likely due to github's cloud hosting)
Switching the URL substantially improves download times. It sill supports both git:// and https://
=> Switch ITK URL to github

SuperBuild/External_VTK.cmake
VTK superbuild has hard-coded https, allow for selection of protocol.
=> Enable git-protocol control on VTK superbuild

Examples/ExtractSliceFromImage.cxx
Use header information so that 3D slices from a 4D volume retain their origin and orientation.
=> ExtractSliceFromImage - use header information for 3D slices

Examples/ImageMath.cxx
Fixed an error in volume calculation in ImageMath's LabelStats function. Volume was being calculated by accumulation, which leads to error with floating point values. Replaced by direct multiplication of voxel volume by voxel count.
=> Fixed floating point error in ImageMath:LabelStats

SuperBuild/External_ITKv4.cmake
Enabling MINC support was breaking nifti loading/writing in ANTs due to MINC support including it's own libnifti. Update to latest MINC resync on ITK to fix.
This fixes #270
=> Update ITKv4 commitid to pull in MINC/libnifti confusion fix

README.md
I recently performed some fixed/moving benchmarks for walltime and memory of antsRegistration.
Thought they might be useful.
=> Add link to benchmarks

Examples/ImageMath.cxx
The PearsonCorrelation function of ImageMath was producing incorrect results (e.g. values outside the expected [-1, 1] range).  The expression to calculate the correlation coefficient has been modified and now produces correct results.  A floating point accumulation error has also been corrected.
=> BUG: Fixed ImageMath's PearsonCorrelation function.

Examples/antsUtilities.cxx
This allows tools such as AverageAffineTransforms to properly read/write MINC xfm files (if ITK has MINC support built in).
Gives comparable results to https://github.com/BIC-MNI/pyezminc/blob/master/examples/xfmavg_scipy.py
=> Enable operating on MINC transforms for some utilities

.travis.yml, CMakeLists.txt
ccache on travis cuts down on build times from ~40 minutes to ~15 minutes
Ex:
https://travis-ci.org/gdevenyi/ANTs/builds/148149544
The *first time* on OSX builds is *very* close to the 50 minute limit on travis, if this is the case, disabling the tests "-DRUN_SHORT_TESTS=OFF" for one cycle will successfully prime the cache.
=> Enable ccache in cmake, and speedup travis builds

ANTS.cmake, Examples/CMakeLists.txt, SuperBuild/External_VTK.cmake
This commit fixes the build system for VTK so that the superbuild works properly.
Through my testing it works for the VTK hash currently set, as well as the very latest 7.x release.
It also still built fine with my system VTK
=> Fix VTK Superbuild

ANTS.cmake, Examples/CMakeLists.txt
These changes in the Examples/CMakelists.txt file allow ANTs to build.  Some changes were made to VTK recently that breaks the ANTs compile.  This successfully built after applying another applying gdevenyi's vtk-fix
=> Vtk examples fix

SuperBuild/External_ITKv4.cmake
With VTK on MINC was missing from config, even if enabled. This fixes this.
=> Add MINC support for config with VTK on

ANTS.cmake
When I added the VTK6/7 test it turns out that was overriding the original COMPONENT search resulting in missing functions in some builds, see #377 
This fixes the problem by moving the complete component find into the IF/ELSE statement.
=> Fix linking components getting overridden by new VTK6/7 test

Examples/SmoothImage.cxx
When blurring high resolution data with large blurs, sometimes the we run into the maximum kernel with of 32. Increase this to a larger number so that in those cases the kernel isn't truncated.
Has no impact to cases where blur kernel isn't truncated because this is just the maximum.
=> Allow for larger kernel sizes in the case of high-resolution data

ImageRegistration/itkLabelImageGenericInterpolateImageFunction.h
ANTs/ImageRegistration/itkLabelImageGenericInterpolateImageFunction.h:66:22: warning: 'EvaluateAtContinuousIndex' overrides a member
function but is not marked 'override' [-Winconsistent-missing-override]
virtual OutputType EvaluateAtContinuousIndex(
When compiling with C++11, use the extra ITK_OVERRIDE to ensure that function
overriding is properly used.
=> COMP: Silence ITK_OVERRIDE warning for virtual methods

Utilities/itkAdaptiveNonLocalMeansDenoisingImageFilter.hxx
Hello,
I am integrating the Adaptive Non-Local Means filter into my own project and noticed it was producing some nonsensical output when compiled as "Debug" with Visual Studio 2013.  After some debugging, I discovered the root cause to be uninitialized values which I found using valgrind's memcheck tool (this time compiled with gcc, of course).  See valgrind report below.
It seems that `itk::Image::Allocate` was used with a `0.0` argument thinking this was the value to fill the buffer with.  That argument is actually a `bool` which, when true, fills the buffer using the type's default constructor.  I did some `grep`ping and did not find `Allocate` used in this way elsewhere.
Thanks
`==7430== Conditional jump or move depends on uninitialised value(s)
==7430==    at 0x6D59151: …
=> BUG: Fix uninitialized image arrays used by denoiser.

Examples/antsJointFusion.cxx, Examples/antsJointTensorFusion.cxx, ImageSegmentation/itkWeightedVotingFusionImageFilter.h, ImageSegmentation/itkWeightedVotingFusionImageFilter.hxx, Utilities/itkAdaptiveNonLocalMeansDenoisingImageFilter.h, Utilities/itkAdaptiveNonLocalMeansDenoisingImageFilter.hxx, Utilities/itkNonLocalPatchBasedImageFilter.h, Utilities/itkNonLocalPatchBasedImageFilter.hxx, Utilities/itkNonLocalSuperresolutionImageFilter.h, Utilities/itkNonLocalSuperresolutionImageFilter.hxx
This is a refactoring of all the patch-based filters (``antsJointFusion``, ``DenoiseImage``, and ``NonLocalSuperResolution``) to all derive from a single parent class.  @stnava  and @hjmjohnson, I think this might be useful to put in ITK proper.
=> ENH:  Refactor all patch-based filters to new parent class.

ANTS.cmake
I'm not sure but removing the spaces from different directories.
This seems to be the only case where I have found that may correspond to warnings such as:
https://travis-ci.org/stnava/ANTsRCore/jobs/248218916#L1193
=> maybe this will remove the warnings

Examples/iMathFunctions.hxx
seems like a small bug in `iMathFillHoles` - the if statements are the same, leading erat to always be 1.0 .. This means `iMath(img, 'FillHoles', holeParam)` automatically fills in every hole even if the hole has low confidence (low `erat`) and just doesnt fill in anything when holeParam = 1 (which i guess is correct result but not for the right reason)
Here's an example of a very easy problem:
iMath works for all cases except when holeParam == 1. With this fix, `erat` now gives an actual confidence value for each of the labels.
```R
img <- antsImageRead("outfile.jpeg")
img.0 <- iMath(img, "FillHoles", 0) # works
img.0 <- iMath(img, "FillHoles", 0.2) # works
img.1 <- iMath(img, "FillHoles", 1) # doesnt work
img.2 <- iMath(img, "FillHoles", 1.2) # works
```
Or maybe I'm missing something …
=> fix bug in iMathFillHoles

Scripts/antsBrainExtraction.sh
Proposing a minor fix to antsBrainExtraction.sh
Looks to me like DIMENSION needed correcting to $DIMENSION for purposes of setting 2D atropos MRF.
=> minor fix for DIMENSION setting in 2D atropos MRF

Scripts/antsMultivariateTemplateConstruction2.sh
The output prefix (-o) in `antsMultivariateTemplateConstruction2.sh` is currently compulsory, but there is a default set in the script.  To make this default work it is only necessary to set a corresponding default for the template name  This pull request makes this change.
This change, although not strictly necessary, is helpful because in the current implementation, if the user forgets to set the output prefix, the script seems to work at first.  It only fails after the first template iteration, which may take a very long time.
=> Set a default output prefix in antsMultivariateTemplateConstruction2.sh

Scripts/antsLongitudinalCorticalThickness.sh
This modification attempts to reduce a bias that occurs when single-time points are processed, resulting in significantly lower cortical thickness values. This bias was found when performing prior cooking, unknown if it exists without cooking. Here we just treat the subjects single image as its  own template and then proceed as usual to ensure that the same cooking process is performed.
=> ENH: treat single time points as their own template

Utilities/itkSurfaceCurvatureBase.h, Utilities/itkSurfaceCurvatureBase.hxx, Utilities/itkSurfaceImageCurvature.h, Utilities/itkSurfaceImageCurvature.hxx
Remove unnecessary redundancy for the SetSigma() between the base class
and the derived class.
ANTs/Examples/SurfaceBasedSmoothing.cxx:7:
ANTs/Utilities/itkSurfaceImageCurvature.h:155:3: warning: 'SetSigma' overrides a member function but is not marked 'override'
itkSetMacro(Sigma, float);
^
ANTs/Examples/SurfaceBasedSmoothing.cxx:71:3: note: in instantiation of template class
'itk::SurfaceImageCurvature<itk::Image<float, 3> >' requested here
ParamType::Pointer Parameterizer = ParamType::New();
^
ANTs/Utilities/itkSurfaceCurvatureBase.h:164:3: note: overridden virtual function is here
itkSetMacro(Sigma, RealType);
^
=> COMP: Fix inconsistency of SetSigma types and overrides

Examples/antsRegistrationOptimizerCommandIterationUpdate.h
Using the `--write-interval-volumes 1` argument of `antsRegistration` caused a segfault on stages that used multiple metrics. Updated the `WriteIntervalVolumes` method of the  `antsRegistrationOptimizerCommandIterationUpdate` class to work with both single-metric and multi-metric stages.
=> Write Interval Volumes with Multiple Metrics

Examples/antsDisplacementAndVelocityFieldRegistrationCommandIterationUpdate.h, Examples/antsRegistrationOptimizerCommandIterationUpdate.h
Having more than 100 iterations in one level causes naming for interval volumes to be sorted incorrectly. This fixes this.
=> Fix for --write-interval-volumes filename padding

Utilities/itkantsReadWriteTransform.h
Fixes #567 upstream: itkantsReadWriteTransform fails if filepath contains .mat, .txt, etc. anywhere
=> Improve transform filetype extension matching

Examples/antsAI.cxx, Scripts/antsBrainExtraction.sh
- Added an option to search translation. Often I deal with data that has different fields of view. The rotation is often correct (head has a consistent orientation with the template) but there is a large initial offset because the center of mass of the template and moving image differs substantially.
With the new option one can add translation in one or more dimensions. Eg, `--translation-search-grid [40, 0x0x40]` only shifts the image in z ny -40mm, 0, 40mm. 
- Search rotations more extensively in 3D by doing rotations about axis1(=x by default), axis2(=y by default) and then axis1 again. 
- Changed default search factor to 20 degrees. Because I've added more start points, I thought it would be sensible to do this. The default arcFraction is still 1.
- Added verbose ouput reporting total …
=> Some changes to antsAI search pattern

ImageSegmentation/antsAtroposSegmentationImageFilter.h
Hello! The return type of that getter method was wrong, breaking compilation on gcc 8.1.0.
=> BUG: fix a bug in ImageSegmentation/antsAtroposSegmentationImageFilter.h

Examples/MeasureImageSimilarity.cxx, Examples/SmoothImage.cxx, Examples/antsAI.cxx, Examples/antsAffineInitializer.cxx, Examples/antsUtilitiesTesting.cxx, Examples/itkantsRegistrationHelper.hxx, SuperBuild/External_ITKv5.cmake
Following the merge here: https://github.com/InsightSoftwareConsortium/ITK/commit/569a4701b740d849a1efe20c9fd76a928c645fbb
I've updated the ITK tag to match.
I also rewrote SmoothImage to use RecursiveGaussian instead of DiscreteGaussian, this fixes #538 
This ITK version ID has a bug with HDF5 implementation (breaks MINCIO) so hold on merge until I get get that fixed and I'll update the hash.
=> Replace DiscreteGaussian with RecursiveGaussian

Scripts/antsJointLabelFusion.sh, Scripts/antsJointLabelFusion2.sh, Scripts/antsLongitudinalJointLabelFusion.sh
Ran into these scripts throwing errors despite having ANTSPATH defined. Looks like some trailing slashes got dropped in the check for the functions.
This way, the check works as long as the path contains the needed commands.
=> Fix ANTSPATH needing trailing slash

Scripts/antsMultivariateTemplateConstruction2.sh
Use pattern matching to avoid the bug in #634 
This will only strip nifti extensions, this may not be whats wanted, if so, happy to add more extensions to the list, however all the documentation, as well as some other hard-coded bits make this script currently not work properly on anything other than nifti.
=> Use pattern matching to remove extensions instead of greedy parameter expansion

Examples/RebaseTensorImage.cxx, Examples/antsApplyTransforms.cxx
Now assume that tensor is based in the moving voxel space, and reorient
to the fixed voxel space before resampling. Same with vectors.
This fixes a bug where the tensors and vectors were transformed in the opposite direction.
RebaseTensorImage had the same error but only when the REFERENCE option was used.
Relates to issue: https://github.com/ANTsX/ANTs/issues/642
Test data and scripts: https://github.com/cookpa/antsDTOrientationTests
=> WIP: Change tensor / vector treatment in antsApplyTransforms

ImageRegistration/itkJensenHavrdaCharvatTsallisLabeledPointSetMetric.h, ImageRegistration/itkJensenHavrdaCharvatTsallisPointSetMetric.h, ImageRegistration/itkVectorParameterizedNeighborhoodOperatorImageFilter.h, ImageRegistration/itkVectorParameterizedNeighborhoodOperatorImageFilter.hxx, Temporary/itkMeanSquaresPointSetToPointSetIntensityMetricv4.h, Temporary/itkMeanSquaresPointSetToPointSetIntensityMetricv4.hxx, Utilities/itkDeformationFieldGradientTensorImageFilter.h, Utilities/itkDeformationFieldGradientTensorImageFilter.hxx, Utilities/itkGeometricJacobianDeterminantImageFilter.h, Utilities/itkGeometricJacobianDeterminantImageFilter.hxx, Utilities/itkOptimalSharpeningImageFilter.h, Utilities/itkOptimalSharpeningImageFilter.hxx
See https://discourse.itk.org/t/warning-dynamic-exception-specifications-are-deprecated-in-c-11/470
Allows to compile against ITK5 w/ `-std=c++17`.
=> COMP: remove deprecated dynamic exception specifiers

Examples/LaplacianThickness.cxx
Relates to my question #688 so may be I am doing something completely inappropriate ;)
Although I have modified that helper message, I am not 100% sure how to digest it since it doesn't really correspond to the code:
```c++
float gmprob = gm->GetPixel(Iterator.GetIndex() );
if( gmprob == 0 )
{
gmprob = 0.05;
}
float sprob = sulci->GetPixel(Iterator.GetIndex() );
sprob = 1 / (1. + exp(-0.1 * (sprob - 0.5) / dosulc) );
sulci->SetPixel(Iterator.GetIndex(), sprob );
```
and the message says
```
... 1/(1.+exp(-0.1*(laplacian-img-value-sulcprob)/0.01)) 
```
=> ENH: LaplacianThickness - make listed values to correspond to defaults and be uniform

Examples/ANTSIntegrateVectorField.cxx, Examples/MeasureImageSimilarity.cxx, Examples/antsAI.cxx, Examples/antsMotionCorr.cxx, Examples/antsSliceRegularizedRegistration.cxx, Examples/itkantsRegistrationHelper.hxx
ANTs/Examples/itkantsRegistrationHelper.hxx:954:35: warning:
explicitly assigning value of variable of type 'typename
MutualInformationMetricType::Pointer' to itself [-Wself-assign-overloaded]
mutualInformationMetric = mutualInformationMetric;
~~~~~~~~~~~~~~~~~~~~~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~~
=> COMP: Remove self assignment warning

CMake/ITKSetStandardCompilerFlags.cmake, CMakeLists.txt
Provide a mechanism for changing the default warning
and ABI/OPTIMIZATION flags.
The default ABI/Optimization flag settings are
set to:
-mtune=native # Tune the code for the computer used compile
-march=corei7-avx # Use ABI settings to support corei7-avx
The defaults can easily be overriden from the cmake comand line with:
-DANTs_C_OPTIMIZATION_FLAGS:STRING="-march=native"
-DANTs_CXX_OPTIMIZATION_FLAGS:STRING="-march=native"
-DANTs_C_WARNING_FLAGS:STRING="-Wall -Werror"
-DANTs_CXX_WARNING_FLAGS:STRING="-Wall -Werror"
=> PERF: Allow overwriting ABI/Optimization & Warning flags

.travis.yml
As per the note here: https://travis-ci.org/ANTsX/ANTs/jobs/549759403
Travis is removing xcode6.4 in "January 2019"
=> Remove depreciated OSX version from travis config

ImageRegistration/itkANTSImageRegistrationOptimizer.h, SuperBuild/External_ITKv5.cmake
The VectorExpandImage filter specialization is no longer needed because
the ExpandImage filter now works with both vector and scalar types
uniformly.
=> COMP: Allow building with ITK_LEGACY_REMOVE turned on

Examples/N4BiasFieldCorrection.cxx, SuperBuild/External_ITKv5.cmake, Utilities/itkN3MRIBiasFieldCorrectionImageFilter.h, Utilities/itkN3MRIBiasFieldCorrectionImageFilter.hxx
Mirrors the N4 changes in ITK [here](https://github.com/InsightSoftwareConsortium/ITK/commit/389da5d8e5dbd433a506c750c7b914ead1482d54#diff-4fd7d6e8f77462fbcf32c75bf3bfe9f8)
=> PERF:  change computation type for fft:  float --> double

ImageSegmentation/antsAtroposSegmentationImageFilter.hxx, Utilities/antsCommandLineParser.cxx, Utilities/itkLabeledPointSetFileReader.hxx
The semi-colon was recently removed to address a
compiler warning about duplicate `;`.  This warning
was also addressed in upstream ITK, and now the the
`;` is required to compile with ITK versions after 11/06/2019.
=> BUG: Restoring semi-colon at end of warning macro

.travis.yml
Trying out this addition to .travis.yml:
```
branches:
only:
- master
```
The idea is to build only the master branch. Pull requests should still get built. If we need to be testing development branches, we can add them here.
There is a button on the Travis UI to turn off branch builds entirely. But then you don't get a build of master after a merge.
My aim is to avoid the situation where one of us makes a small change and a PR, and then both the branch commit itself and the PR are building at the same time.
The alternative as previously suggested by @gdevenyi is for all of us to fork ANTs and then issue PRs from there.
=> COMP: Trying to reduce the Travis overhead by only building master + PRs

Examples/N3BiasFieldCorrection.cxx
It looks like there is a bug in the argument parsing for N3BiasFieldCorrection.
=> Update order of arguments in N3BiasFieldCorrection

Examples/antsApplyTransforms.cxx
Adds an antsApplyTransforms option --odt to set output datatype, via itkCastImageFilter before writing the output image to disk (internal computations remain in double or float regardless). Our typical use case applies antsApplyTransforms to propagate a library of atlases where values are integers <255, so there are large gains in disk space efficiency and I/O time by writing these as uchar rather than double. It would be possible to convert externally after writing, but this would not be I/O efficient.
--odt char
uchar
short
int
float
double
default
Output image data type. This is a direct typecast; output values are not 
rescaled. Default is to use the internal data type (float or double). uchar is 
unsigned char; others are signed. WARNING: Outputs will be incorrect if values 
exceed …
=> antsApplyTransforms: add option -odt to set output datatype

Examples/TimeSCCAN.cxx
ANTs/Examples/TimeSCCAN.cxx:866:32: warning:
object backing the pointer will be destroyed at the end of the full-expression [-Wdangling-gsl]
const char *longName = ( ( *it )->GetLongName() ).c_str();
^~~~~~~~~~~~~~~~~~~~~~~~~~
1 warning generated.
error: cannot assign to non-static data member within const member function 'operator()'
=> COMP: Assigning non-static data member within const member

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/other_questions.md
I've added a config file that will direct people to ANTsR or ANTsPy for issues with those tools.
I also disabled the blank issue, and tried to clarify when people should use the other templates. I added a general questions template to replace the blank issue, with reminders to use the appropriate template for bugs / runtime issues or build errors.
=> ENH: Updating issue templates

Examples/N3BiasFieldCorrection.cxx, Utilities/itkN3BiasFieldCorrectionImageFilter.h, Utilities/itkN3BiasFieldCorrectionImageFilter.hxx
Since N3 gets used quite a bit, I've always wanted to refactor it so that it has some of the add-ons that we've provided for N4.  I think N3 should use the ANTs command line interface.  So I have to do more testing but I think this works.  In order to access the refactored N3, one needs to simply add an 'x' after N3BiasField correction, i.e.,
```
N3BiasFieldCorrection x -h 1
COMMAND: 
N3BiasFieldCorrection
OPTIONS: 
-d, --image-dimensionality 2/3/4
-i, --input-image inputImageFilename
-x, --mask-image maskImageFilename
-r, --rescale-intensities 0/(1)
-w, --weight-image weightImageFilename
-s, --shrink-factor 1/2/3/(4)/...
-c, --convergence [<numberOfIterations=50>,<convergenceThreshold=0.0>]
-b, --bspline-fitting [splineDistance,<numberOfFittingLevels=4>,<splineOrder=3>] …
```
=> WIP:  Add N4 bells and whistles to N3.

Dockerfile
There's an issues with CMake 3.19 that breaks compilation of ITK. ITK has downgraded to 3.18.3 until it's fixed. See
https://gitlab.kitware.com/cmake/cmake/-/issues/21529
=> COMP: CMake 3.19 has problems with ITK, set version to 3.18 in Docker

Scripts/antsRegistrationSyN.sh, Scripts/antsRegistrationSyNQuick.sh
Eg, `-g 0.2`. The default is unchanged (0.1). 
I've found that 0.1 can sometimes be too conservative at the SyN stage.
=> ENH: Add option for SyN gradient step in scripts

.circleci/config.yml, Dockerfile
Adding a label at build time to identify the source code version from an automated build using docker inspect.
=> DOC: Include version information and citation in docker images

.circleci/config.yml
Changing the TZ variable as suggested in the CircleCI docs
=> ENH: Fix timezone for CircleCI Docker builds

.circleci/config.yml
There's a regex so that tags matching v0.0.0 should be pushed
=> ENH: Hopefully push tagged versions to DockerHub

Scripts/antsRegistrationSyN.sh, Scripts/antsRegistrationSyNQuick.sh
These changes allow the user to control the random seed in repro mode (as suggested in #1189).
Also expanded upon the usage a bit
=> ENH: Allow user to set random seed in repro mode

Scripts/antsCookTemplatePriors.sh
Replace ThresholdImage with call to ImageMath WindowImage, clipping priors < 0 to 0 and priors > 1 to 1.
=> BUG: Fix precision issues causing priors to get zeroed out

Examples/AverageImages.cxx, Scripts/antsMultivariateTemplateConstruction.sh, Scripts/antsMultivariateTemplateConstruction2.sh
Fixes #1216. In addition to enforcing the use of AverageImages in population average templates, I made a few tweaks to help convergence:
* Use @gdevenyi 's idea to do a COM alignment of each image to the initial average
* Don't sharpen the population average, resulting in a smoother initial template 
* Also don't sharpen after the initial rigid alignment
After the population average + initial rigid stage, the statistic (mean, normalized mean, median) and sharpening options follow whatever the users specify on the command line.
In order to make the process more transparent to users, I added an output folder `intermediateTemplates/`, which contains each template and, if it exists, the template shape update. This will let users visually inspect their templates at every stage, and the update …
=> Template initialization to improve convergence

Scripts/antsIntermodalityIntrasubject.sh
Hi!
I've been running antsIntermodalityIntrasubject.sh and noticed that even though I am providing the brain mask, it is not included in the running "summary". While confusing at first, I then found the issue and the wrong parameter is being used in the summary.
You can see the differences here.
Before:
After:
Also, I fixed a small typo.
Thanks!
=> BUG - antsIntermodalityIntrasubject.sh - fixed a typo and incorrect running summary

ImageSegmentation/itkWeightedVotingFusionImageFilter.h, ImageSegmentation/itkWeightedVotingFusionImageFilter.hxx
Two bugs were identified when using uncommon parameters for ants joint fusion.
=> Fix joint fusion bugs multi modal data

ImageSegmentation/itkWeightedVotingFusionImageFilter.hxx
A hasty git PR missed adding obvious code syntax fixes.
=> COMP: Fix compilation syntax errors from failed build

SuperBuild/External_ITKv5.cmake, SuperBuild/External_VTK.cmake
Older versions of ITK and VTK introduced compiler warnings
with new more pedantic compilers.  VTK warned of duplicate
symbols, and ITK warned of empty statements.
Code built and tests passed:
100% tests passed, 0 tests failed out of 130
=> COMP: Update ITK and VTK to avoid compiler warnings

Examples/antsApplyTransforms.cxx
HDF5 vector images don't work with transform readers.
=> ENH: Allow writing HDF5 transforms as ITK transforms 

SuperBuild.cmake
Github no longer supports unauthenticated git://
=> ENH: Use https for git URLs

.github/workflows/ci-docker.yml, README.md
COMP: Avoid building on draft PR
=> DOC: Docker CI badge in README

Dockerfile
=> BUG: Need to install bc in final layer

Examples/antsMotionCorr.cxx
Previously, affine transforms used the registration method default (mm) while deformable transforms used voxels. 
Made them consistent with antsRegistration, allowing AxBxCmm or AxBxCvox specification.
=> ENH: Allow smoothing to be specified in mm or vox

Examples/antsRegistration.cxx, Examples/antsRegistrationTemplateHeader.h, Examples/itkantsRegistrationHelper.h, Examples/itkantsRegistrationHelper.hxx, Examples/simpleSynRegistration.cxx
Partially an attempt to address [this issue](https://github.com/ANTsX/ANTs/issues/1348) but might be more generally useful.  Allows users to specify using gradient filter for image metric gradient calculation.  Should be backwards compatible.
=> ENH:  Expose UseGradientFilter variable for image metrics.

Examples/antsMotionCorr.cxx
Partially attempts to address [this issue](https://github.com/ANTsX/ANTs/issues/1348).  Expose gradient filter usage option for metrics.
=> ENH:  Expose gradient filter option for metrics.

Scripts/antsMultivariateTemplateConstruction2.sh
Updating template registration documentation, as mentioned in #1347
=> DOC: Better explain options

Examples/PrintHeader.cxx
Current ITK clone seems to include some changes to the enumerated types for spatial orientation.  
Putting this here for when we update ITK.
=> WIP:  Changes for updating to current ITK.

Utilities/tagRelease.pl
The post-release commit just resets a flag, no need to push a docker image
=> ENH: Skip CI on the post-release commit

.github/workflows/release-binaries.yml
This runner script builds ANTs for Ubuntu and Mac. It uses static binaries, which are larger, but avoid having to deal with location issues.
=> ENH: Attach binaries to releases

Examples/antsAI.cxx, Examples/antsCommandIterationUpdate.h
Proof of concept for progress reporting in `antsAI`. Currently prints every iteration, which is potentially a lot - could be smarter and print progress at intervals.
Fixes #439
=> ENH: Progress reporting for antsAI

.github/workflows/release-binaries.yml, .github/workflows/release-docker-binaries.yml
This can be extended to other platforms that aren't supported by native runners.
Also made some improvements for readability to the native release binary build
Swapped out the artifact uploader to one that retries if there's a network error
=> ENH: Use docker to build Centos binaries

Scripts/antsRegistrationSyN.sh, Scripts/antsRegistrationSyNQuick.sh
This was kind of an undocumented feature because you could do `-x fixedMask.nii.gz,movingMask.nii.gz` and it would work. The script would change the arg to `-x [ fixedMask.nii.gz,movingMask.nii.gz, NULL ]`. 
I changed it so that `-x fixedMask.nii.gz,movingMask.nii.gz` maps to `-x [ fixedMask.nii.gz,movingMask.nii.gz ]` and `-x fixedMask.nii.gz` maps to `-x [ fixedMask.nii.gz, NULL ]` as before.
=> ENH: Allow fixed,moving masks in scripts

Examples/antsMotionCorr.cxx, Examples/antsRegistration.cxx, Examples/antsRegistrationTemplateHeader.h, Examples/itkantsRegistrationHelper.hxx
I'm guessing this is a legacy option before we switched to the conjugate gradient descent optimizers for everything but the exponential transforms.   But even those don't use this flag as no scales estimator is applied in these two cases (B-spline and Gaussian).
Addresses #1405
=> WIP:  Remove unused estimate learning rate at each iteration.

Scripts/antsRegistrationSyN.sh, Scripts/antsRegistrationSyNQuick.sh
It's easy to miss the printout of the antsRegistration call when using the scripts, because it gets scrolled off the screen. So I repeated it at the end.
=> ENH: Output extra info at the end of registration

Examples/Atropos.cxx
added missing end parenthesis to Atropos' use-euclidean-distance parameter documentation.
=> DOC: added missing end parenthesis to Atropos documentation string

ANTS.cmake, SuperBuild/External_ITKv5.cmake
=> BUG: Remove hard-coded lib dir that was breaking centos builds

Examples/AverageImages.cxx
DOC: Clarify normalization options only apply to single component input
=> ENH: Check AverageImages input files can be read

Scripts/antsAtroposN4.sh
when trying to optimize antsAtroposN4.sh execution speed contra output precision it would be great to expose these internal variables as external cli parameters
=> ENH: antsAtroposN4.sh - exposed more subcommand parameters as arguments

Examples/Atropos.cxx
bug can be reproduced by:
```
wget https://openneuro.org/crn/datasets/ds004288/snapshots/1.0.1/files/sub-0303:anat:sub-0303_T1w.nii.gz
mkdir tmp_test
Atropos -x sub-0303:anat:sub-0303_T1w.nii.gz -a sub-0303:anat:sub-0303_T1w.nii.gz -o [ tmp_test/Segmentation.nii.gz,tmp_test/SegmentationPosteriors%d.nii.gz ]
```
this currently segfaults, the patched code instead prints an error message to explain to the user what is wrong.
=> BUG: Atropos no longer segfaults when -i is missing, it reports an error msg instead

Scripts/antsAtroposN4.sh
Scripts/antsAtroposN4.sh was not stopping as "${PIPESTATUS[0]}" was always 0, this happened because of "logCmdOutput=" which I this starts a subshell which have the PIPESTATUS variable inside it, but this variable is not visable outside the subshell. The PIPESTATUS is now instead return by the subshell and its exitcode is inserted into cmdExit.
commands use to reproduce the problem:
```
wget https://openneuro.org/crn/datasets/ds004288/snapshots/1.0.1/files/sub-0303:anat:sub-0303_T1w.nii.gz
mkdir tmp_antsAtroposN4
ANTSPATH=/usr/bin/ time ./deps/ANTs/Scripts/antsAtroposN4.sh -d 3 -c 3 -m 3 -n 3 -a sub-0303\:anat\:sub-0303_T1w.nii.gz -o tmp_antsAtroposN4/ -u 0 -e "[35x35x35x35,0]" -f 4
```
which should fail because of the missing -x parameter.
=> BUG: fixed Scripts/antsAtroposN4.sh not stopping when subcommands exit with exitcode>0

Scripts/antsAtroposN4.sh
Thanks to #1456, the script will now exit after failing to run Atropos if the mask is missing, but it can be several minutes until it gets to that command. Now exit immediately after explicitly checking the mask.
=> BUG: Needed to exit immediately if mask is missing

ImageSegmentation/antsAtroposSegmentationImageFilter.hxx
This is a reimplementation of the optimizations initially proposed in PR https://github.com/ANTsX/ANTs/pull/1452
With the help of the ITK discourse forum in post https://discourse.itk.org/t/how-to-use-itk-multi-threading-primitives-to-do-parallel-execution-of-loop-iteration/5531/ I have managed to rework my previous proof of concept implementation into a generic solution that uses the ITK multi-threading primitive ParallelizeImageRegion.
During my limited testing (using only two image inputs) I have seen the execution time being reduced to around 60-70% of the original implementations execution time. The execution times for the two tested image inputs: image 1 was reduced from 96 seconds to 60 seconds (see below) and image 2 from 272 seconds to 168 seconds.
I have validated the …
=> PERF: accelerating antsAtroposSegmentationImageFilter.hxx function GetPosteriorProbabilityImage using ITK ParallelizeImageRegion

Scripts/antsBrainExtraction.sh
This enables identical results from multiple runs of brain extraction by using "-u 0". Previously, this was achieved by setting ANTS_RANDOM_SEED along with "-u 0". Now, "-u 0" also sets ANTS_RANDOM_SEED within the script if it is not already defined
=> ENH: Make "-u" option also set a random seed for registration

SuperBuild/External_ITKv5.cmake
This only affects registration with metric sampling strategies in the SyN / BSplineSyN stages. Dense sampling is not randomized.
Fixes #1475 and #1470
=> BUG: Bump ITK to fix random seeding for SyN

.github/workflows/release-binaries.yml, .github/workflows/release-docker-binaries.yml, .github/workflows/release-win-binaries.yml, SuperBuild/External_ITKv5.cmake
* COMP: Switch to ITK zlib
Using ITK zlib avoids having to build zlib on Windows. Appears to build fine on other platforms also. Fixes #1481
* ENH: Build windows binaries for releases
* ENH: Run tests on release
=> ENH: Use ITK ZLIB, test release builds, Windows binaries (#1)

.github/workflows/ci-docker.yml
Missed this before because docker login doesn't get called until merge. Hopefully the update resolves the node.js deprecation warnings
=> COMP: Update docker login action

Utilities/ReadWriteData.h
Inspired by https://github.com/ANTsX/ANTsPy/issues/437
Notice from the exception thrown there:
```
file 0000018600E3C1C0 does not exist . 
Exception Object caught: 
itk::ExceptionObject (0000000A275EBBC0)
Location: "unknown" 
File: D:\a\ANTsPy\ANTsPy\itksource\Modules\Registration\Common\include\itkCenteredTransformInitializer.hxx
Line: 31
Description: ITK ERROR: CenteredTransformInitializer(000001867F47D310): Fixed Image has not been set
```
On Windows the address is "0000018600E3C1C0" not "0x000018600E3C1C0", so it won't match the "0x" pattern, and ANTs attempts to read as a file from disk.
I've tried to modify the logic so that a hex string of the appropriate length (17 chars here) gets treated as a pointer also. My hope is that this will allow ANTsPy to work on Windows, but I can't …
=> ENH: Read Windows pointers

SuperBuild.cmake
This is a minimal dependency change for the build (just libminc2 in ITK) and the ANTs tools show `--minc` regardless of this switch so I think its better to enable by default.
=> Enable MINC support by default

Examples/LabelGeometryMeasures.cxx
Skips intensity image if placeholder "none" or "na" is used (case insensitive). Exit with error if some other value is given and the file cannot be read.
Fixes #1522
=> ENH: Clarify usage, skip intensity image if it is "none" or "na"

Examples/antsAI.cxx
Mattes is used in antsRegistration and works better for on human brain images.
I considered removing MI altogether, but I don't know if it might be useful for some images (or if it's any faster), so I just moved it down the list and noted that Mattes is recommended.
=> DOC: Recommend Mattes MI as the default metric

.github/workflows/release-docker-binaries.yml
Github deprecated the Ubuntu 18.04 runners so these no longer build natively. But 18.04 remains the most popular platform for downloads, so I thought we should continue to provide it.
=> ENH: Add Ubuntu 18.04 builds via docker

Scripts/antsBrainExtraction.sh, Scripts/antsCorticalThickness.sh
Set a random seed with `-u 0`, if one is not already defined.
=> ANTsCT random seed

CONTRIBUTING.md
=> WIP: Add CONTRIBUTING.md

Examples/ImageMath.cxx, Examples/ImageMath_Templates.hxx, Examples/antsVol.cxx, Scripts/antsMultivariateTemplateConstruction.sh, Scripts/antsMultivariateTemplateConstruction2.sh
Add option to sharpen without using the image spacing.  Explicitly turn off in template building.  Addresses https://github.com/ANTsX/ANTs/issues/1540.
=> ENH:  Add spacing option for laplacian sharpening.

Examples/antsRegistrationTemplateHeader.h
https://github.com/ANTsX/ANTs/issues/1561#issuecomment-1619077395
Try this.  
When "collapsing the transforms" the composite transform member variable is getting mangled somehow.  The output transforms written to disk appear to be correct but the mangling affects the warped image so I simply reordered the output which admittedly is a temporary fix but a potential fix nonetheless.
=> BUG: Avoid composite transform mangling.

Scripts/antsMultivariateTemplateConstruction.sh, Scripts/antsMultivariateTemplateConstruction2.sh
antsMultivariateTemplateConstruction*.sh were repeating N4 correction on the raw input images every iteration. Skip doing N4 if the file exists.
Fixes #1590
=> Fix: don't repeat N4 every iteration

Examples/sccan.cxx
functions in sccan.cxx
There was an if statement in the code that should have used the new `random_shuffle` and not the old `std:shuffle` that has been removed in c++-17.
I don't know why this stopped working, but the Windows runner would not build the latest release, so I removed the if statement and just used the updated function `random_shuffle`.
Fixes #1593
=> COMP: Github windows runners were attempting to use deprecated

Examples/AverageAffineTransform.cxx
Report a specific error message if ImageDimension is omitted. Also clarify that .mat files are supported as well as .txt files
Fixes #1602
=> ENH: Clarify usage and catch missing ImageDimension

Examples/KellyKapowski.cxx, Utilities/itkDiReCTImageFilter.h, Utilities/itkDiReCTImageFilter.hxx
```bash
input=test.nii.gz
outputPrefix=thickness
KellyKapowski -d 2 \
-s "[${input},1,2]" \
-o "[${outputPrefix}.nii.gz,${outputPrefix}]" \
-v 1
ConvertImage 2 ${outputPrefix}InverseVelocityField.nii.gz ${outputPrefix}InverseVelocityField 11
for i in {1..9}; 
do 
ExtractSliceFromImage 3 ${outputPrefix}InverseVelocityFieldxvec.nii.gz ${outputPrefix}InverseFieldxvec.nii.gz 2 $i
ExtractSliceFromImage 3 ${outputPrefix}InverseVelocityFieldyvec.nii.gz ${outputPrefix}InverseFieldyvec.nii.gz 2 $i
ConvertImage 2 ${outputPrefix}InverseField ${outputPrefix}InverseField.nii.gz 9
antsApplyTransforms -d 2 -i ${input} \
-r ${input} \
-o testWarped${i}.nii.gz \
-n NearestNeighbor \
-t ${outputPrefix}InverseField.nii.gz  
done
TileImages 3 testWarped.nii.gz 1x1x0 testWarped?.nii.gz
rm -f …
```
=> ENH:  Expose forward/inverse cumulative velocity fields.

Scripts/antsMultivariateTemplateConstruction.sh, Scripts/antsMultivariateTemplateConstruction2.sh
As evidenced in #1634
This bug affects users who run `antsLongitudinalCorticalThickness.sh` or `antsMultivariateTemplateConstruction[2].sh`.
The bug only affects use cases where `-n 1` is passed to the template script **and** the input base names are identical. For example,
`antsLongitudinalCorticalThickness.sh [options] /data1/t1w.nii.gz /data2/t1w.nii.gz`
`antsMultivariateTemplateConstruction.sh [options] -n 1 /data1/t1w.nii.gz /data2/t1w.nii.gz`
=> BUG: Template input overwritten when basename identical

Scripts/antsMultivariateTemplateConstruction.sh, Scripts/antsMultivariateTemplateConstruction2.sh
Name output files by position in input, rather than by tuple
=> ENH: Better to use actual index into imageset array

Scripts/antsBrainExtraction.sh
Addressing #1638.
Updated N4, downsampling procedure to not smooth and downsample non-human or neonate images too much.
I exposed the antsAI search parameters to the user because I think they are harder to guess from the input compared to the downsampling. The defaults are unchanged.
=> Make antsBrainExtraction.sh less sensitive to image size

Examples/ImageMath_Templates.hxx, Utilities/antsCommandLineOption.h
Legacy removal is forced to ON [when wrapping is enabled](https://github.com/InsightSoftwareConsortium/ITK/blob/c8ec91c826898838f5f1a1a2a53849dd3efc9c88/CMakeLists.txt#L305-L310). Prepare ANTs for building in such a scenario. We will need it soon in https://github.com/thewtex/ANTsWasm.
=> COMP: Fix some compile errors when legacy functionality is removed

Examples/sccan.cxx, SuperBuild/External_ITKv5.cmake
=> COMP: Fix compile warning C4858: discarding return value in std::remove

Examples/antsDisplacementAndVelocityFieldRegistrationCommandIterationUpdate.h, Utilities/itkantsReadWriteTransform.h
This happens when these files are used directly,
and not through default ANTs build system.
=> COMP: Add missing include headers

.dockerignore, Dockerfile
Run the short tests during the Docker build, add an option to turn off shared libs
=> ENH: Allow static libs, re-enable testing

.github/workflows/release-binaries.yml
With the new M1 runner, we can provide binaries for Apple Silicon
=> ENH: Use new M1 runner

SuperBuild/External_ITKv5.cmake
https://github.com/InsightSoftwareConsortium/ITK/commit/671d758ac3bd54574b997032d8f72d8467e0dcea
=> ENH: Update ITK to incorporate faster point set checks

Utilities/itkAverageAffineTransformFunction.h, Utilities/itkAverageAffineTransformFunction.hxx, Utilities/itkAverageAffineTransformNoRigidFunction.h, Utilities/itkAverageAffineTransformNoRigidFunction.hxx
So far, this was only possible with double parameters.
=> ENH: Support averaging affine transforms with float parameters

.github/workflows/ci-docker.yml, .github/workflows/release-binaries.yml, .github/workflows/release-docker-binaries.yml, .github/workflows/release-win-binaries.yml
=> COMP: Update actions to avoid node deprecation warnings

ImageRegistration/itkANTSAffine3DTransform.hxx, Utilities/itkAverageAffineTransformFunction.hxx
3D case outputs more debug parameters from within the transform itself. This is a follow-up to #1684.
=> ENH: Display debugging parameters only when verbose flag is turned on

Utilities/itkDiReCTImageFilter.hxx
https://github.com/ANTsX/ANTsPy/issues/579
=> BUG:  Need to fill buffer for R and Python interfaces.

ImageRegistration/itkANTSCenteredAffine2DTransform.hxx
This warning show up a lot for me (e.g. from [here](https://github.com/dzenanz/ANTsWasm/commit/e85adc1959b80fc5252a5579cab1866e7cc4e615)). Should I be concerned?
Example of occurrence:
```log
Progress  | 0 | 0.01 | 0.0345 | 0.059 | 0.0835 | 0.108 | 0.1325 | 0.157 | 0.1815 | 0.206
| 0.2305 | 0.255WARNING: In C:\Dev\ANTsWasm\VS22py\_deps\ants_inner-src\ImageRegistration\itkANTSCenteredAffine2DTransform.hxx, line 138
ANTSCenteredAffine2DTransform (000002581E7CA7F0): Bad Rotation Matrix 1.02555 -0.00607706 0.00711725 1.02636
WARNING: In C:\Dev\ANTsWasm\VS22py\_deps\ants_inner-src\ImageRegistration\itkANTSCenteredAffine2DTransform.hxx, line 138 ANTSCenteredAffine2DTransform (000002581E930950): Bad Rotation Matrix 1.0038 0.000658097 0.0181835 1.0196
WARNING: In …
```
=> ENH: Suppress "Bad Rotation Matrix" warnings

Examples/KellyKapowski.cxx
Now fixed, code is only reachable if `-d` option is missing, so I think this won't break R / Py interfaces
=> BUG: KellyKapowski could not infer dimensionality from input

.github/workflows/ci-docker.yml
If multiple pushes are made to the same branch or PR, cancel prior CI runs
Avoids wasting time and also prevents dockerhub getting out of sync
=> COMP: Cancel previous ci builds

Examples/antsApplyTransforms.cxx
This checks that scalar input to `antsApplyTransforms` is actually an N-dimensional scalar image, and if it's not, exit with error advising users to use the correct input flag with `-e`.
It's my opinion that it's wise to inform users of fatal errors even if they don't use `--verbose`, but if that's going to break anything I can hide the error message for non-verbose execution.
=> ENH: Check input for antsApplyTransforms matches dimensionality

.github/workflows/ci-docker.yml
These were originally part of version labels but now we use X.Y.Z not vX.Y.Z. Makes sense to do the same for Dockerhub
=> CI: Drop v from release versions

Examples/LabelGeometryMeasures.cxx
Not a fix but part of the way to fixing #1733 
I replaced the filter and added some new features including computing mean and median intensities of gray images.
Some attributes don't have an exact analog. I changed some headers to be general over 2D / 3D
New columns are
Label
NumberOfVoxels
PhysicalSize - area in 2D (mm^2) or volume in 3D (mm^3)
Perimeter - perimeter in 2D or surface area in 3D
Elongation - Note this differs from old implementation
Roundness - new
Flatness - new
Centroid_x - Note this differs from old implementation
Centroid_y
Centroid_z
BoundingBoxLower_x - reordered (open to changing this)
BoundingBoxLower_y
BoundingBoxLower_z
BoundingBoxUpper_x
BoundingBoxUpper_y
BoundingBoxUpper_z
MeanIntensity - Grayscale stats if intensity image provided
SigmaIntensity …
=> ENH: Update LabelGeometryMeasures to not use deprecated filter

Examples/LabelGeometryMeasures.cxx
Related to #1733 
Given a 3D object with principal moments V_0 <= V_1 <= V_2, itkShapeLabelMapFilter computes elongation as sqrt(V_2 / V_1).
It doesn't compute eccentricity, so I had added that to LabelGeometryMeasures as sqrt(1 - V_2^2 / V_0^2).
But I think it might be better to use sqrt(1 - V_2^2 / V_1^2), so that it works on the same moments as the elongation. For cortex and other thin structures, the relative shape of the longer sides are often more interesting anyway.
The new filter also has roundness, which is a measure of similarity to a sphere and considers all three axes.
=> ENH: Make eccentricity more similar to elongation

README.md
This proposed PR updates and reformats the README. It is best to view it visually on my fork at https://github.com/ncullen93/ANTs instead of the raw file. 
Improvements:
- You don't have to leave the readme to learn how to install ANTs in a basic scenario.
- All learning resources are grouped together so when I’m in “learning mode” I can quickly evaluate which one I need.
- Same with scripts / example code that are now grouped a bit more semantically. 
- For references, article titles are displayed so I can quickly evaluate which are relevant rather than having to follow a ton of links that take me away from the readme.
- In general, it's much clearer now when you're nevigating to a script, to a tutorial, or to a journal article. It was a complete lottery what I’m going to get from the …
=> ENH: update and reformat README

Examples/antsTransformInfo.cxx
I'd like to be able to easily extract the determinant of affine transforms and antsTransformInfo seems like the right place.
The function has been refactored to handle reading errors.
Based primarily off
https://github.com/InsightSoftwareConsortium/ITK/blob/master/Examples/IO/TransformReadWrite.cxx
Things that aren't done:
- I don't know how to automatically handle the 2D vs 3D transforms. The previous simple read/print code didn't seem to need it whereas this version does.
=> Refactor antsTransformInfo to add some error handling and compute determinant

ImageSegmentation/antsAtroposSegmentationImageFilter.hxx, ImageSegmentation/antsManifoldParzenWindowsListSampleFunction.hxx
Addresses https://github.com/ANTsX/ANTs/issues/1664.
The different likelihood functions (e.g., Gaussian, ManifoldParzenWindows) are generated from a list of samples.  For example, in the classic three tissue scenario, the voxels labeled as 'CSF' for the current iteration are fed into the first likelihood function which are used to estimate the likelihood function parameters (e.g., Gaussian mean).  When I first wrote this, once these parameters were estimated, the samples were no longer needed so I wrote a function to clear the input sample list immediately after likelihood parameter estimation.  However, this is no longer the case with the ManifoldParzenWindows, which relies on the Kdtree class which apparently needs to know the size of the input sample list during evaluation.    This …
=> BUG:  Manifold parzen windows.

Scripts/antsMultivariateTemplateConstruction2.sh
were broken if transform option had parameter brackets.
Fixed now to output eg SyN_intermediate... instead of SyN[ 0.25 ]_intermediate...
=> BUG: intermediate template file names 

ImageSegmentation/antsAtroposSegmentationImageFilter.hxx
Proposed solution to https://github.com/ANTsX/ANTs/issues/1765.
=> BUG:  Address degenerate case.

Scripts/antsMultivariateTemplateConstruction2.sh
A few fixes
* Replaced all the "let" statements and other traps that prevent running with `bash -e`, and turned that on.
* Fixed error checking in pairwise registration stage
* Attempted to make output more readable by prefixing input indices, rather than adding them at the end. Trying to make things easier to list and review, especially with multiple modalities
=> ENH: write template output such that things sort together

Scripts/antsMultivariateTemplateConstruction2.sh
Affects template construction with the bash "strict mode". Replaced ((VAR++)) with VAR=$(( VAR + 1))
=> BUG: VAR=0; ((VAR++)) fails on Linux but not on Mac

README.md
This PR proposes to fix the link to `ANTsPy` in the main README which currently points to `ANTsR`.
=> DOC: Fix wrong link for ANTsPy in README

.github/workflows/release-binaries.yml, .github/workflows/release-docker-binaries.yml
* Replace Centos7 with AlmaLinux 8
* Remove macos-11 build (runner removed by Github)
=> ENH: CI updates

ImageSegmentation/antsAtroposSegmentationImageFilter.hxx
Fixes #1791 
@ntustison , I tried replacing RealType with double in the segmentation filter, but it caused a lot of compile errors, including Atropos.cxx and the ParzenWindow classes. So I just changed the posterior summation here.
=> BUG: float type for posterior sum caused overflow on large images

Examples/antsMotionCorr.cxx
Fixes misleading usage in #1797
=> DOC: Usage, --write-displacement 0

Examples/antsMotionCorr.cxx
=> DOC: Clarify -a usage

Examples/antsApplyTransforms.cxx
A common use case is to register a time series to a scalar reference, then apply the warp to each volume. Sometimes, users will have different transforms for each volume (say, motion correction in fMRI). Other times, the time series might be very large after resampling into the fixed space.
This commit adds an option --time-index, which allows the user to select a particular volume. This is then extracted and transformed as a scalar image.
Fixes #1555
=> ENH: apply transform to single slice of time series

Utilities/ReadWriteData.cxx, Utilities/ReadWriteData.h
Check if the imageIO object can be created on read
This helps avoid seg faults if the file exists but is not a supported image or is corrupt
Will still need downstream code to actually check if ReadImage returns false
=> ENH: More image read checks

.github/workflows/release-binaries.yml
Mac OS 12 runners will be deprecated soon
=> CI: Update macos to 13

Scripts/antsRegistrationSyN.sh, Scripts/antsRegistrationSyNQuick.sh
If using -t so or -t bo, the COM initialization is usually not wanted
=> ENH: identity init transform for (bspline)syn-only

Examples/antsAI.cxx
Use a rigid transform type with identity matrix. This is what antsRegistration does with `-r [ fixed, moving, 1 ]`.
Avoids having to deal explicitly with translation-only transforms in antsTransformInfo
This bypasses #1819 though I think it would be good to merge error checks in #1820 anyway.
=> ENH: Make COM translation consistent with antsRegistration

Scripts/antsRegistrationSyN.sh, Scripts/antsRegistrationSyNQuick.sh
https://github.com/ANTsX/ANTs/issues/1828
=> ENH:  Change radius and gradient step defaults.

Scripts/antsCorticalThickness.sh, Scripts/antsMultivariateTemplateConstruction.sh, Scripts/antsMultivariateTemplateConstruction2.sh
Have left antsBrainExtraction.sh alone because I'm not sure if histogram matching is more important where Laplacians are involved
Trying to harmonize with #768 and #770 in ANTsPy.
There are a lot of specialized / old scripts that I didn't change, we should consider moving to a permanent archive.
Histogram matching also defaults to on in antsMotionCorr, but again that is kind of a specialized case
=> ENH: Update default gradient step, turn off histogram matching

Examples/antsRegistrationOptimizerCommandIterationUpdate.h, Examples/antsRegistrationTemplateHeader.h, Examples/itkantsRegistrationHelper.h, Examples/itkantsRegistrationHelper.hxx
This PR changes the behavior of `--write-interval-volume` to use the prefix of the first parameter from `--output` as the write location, instead of `$PWD`.
Fixes #1836
=> ENH: use prefix of 1st param from --output for --write-interval-volumes

Examples/CompositeTransformUtil.cxx, Examples/antsApplyTransforms.cxx
antsApplyTransforms only allowed users to collapse linear transforms into a single .mat file, or composite transforms into a single displacement field.
Now allow users to write the full composite transform. This enables users familiar with `antsApplyTransforms` to write out composite transforms by specifying the components in the order they are applied when warping images. That is, one can call `antsApplyTransforms -o warpedImage` and then `antsApplyTransforms -o CompositeTransform[composite.h5]` without changing the `-t` options.
The motivation is to make it easier to write composite transforms, since CompositeTransformUtil requires users to use the internal "reverse queue order" of itkCompositeTransform.
The changes are backwards compatible, but I have noted in the usage that we prefer …
=> Write composite transforms from antsApplyTransforms

Examples/antsDisplacementAndVelocityFieldRegistrationCommandIterationUpdate.h, Examples/itkantsRegistrationHelper.hxx
While doing more testing with the changes from #1838, I realized that `Examples/antsDisplacementAndVelocityFieldRegistrationCommandIterationUpdate.h` also needed to be changed to write interval volumes using the first prefix of `--output` when using SyN transform.
Related to #1838
=> ENH: use prefix from --output for --write-interval-volumes

Scripts/antsMultivariateTemplateConstruction.sh, Scripts/antsMultivariateTemplateConstruction2.sh
CSV parsing problems like #1844 have happened before, removing the carriage return avoids the problem
=> ENH: Strip carriage returns from template input

SuperBuild/External_ITKv5.cmake
Hey @cookpa , it's been about a year since we've updated ITK.  I recently fixed an ITK bug that affects some tools in the ANTsX ecosystem and would like to reflect the ITK changes here.  Any potential issues that you're aware of?
=> ENH:  Update ITK tag.

Examples/CreateTiledMosaic.cxx, SuperBuild/External_ITKv5.cmake
This was because it tried to write the mosaic with RealType pixels, which many formats do not support.
COMP: Bump ITK version string in cmake
=> BUG: CreateTiledMosaic would not write images without an RGB overlay

Examples/LabelGeometryMeasures.cxx
This contains more fixes for LabelGeometryMeasures.
The median was only added relatively recently, when switching out the deprecated ITK filter. But it is approximated and derived from a histogram, the default is to use 255 bins over the whole range of the image. This can get really imprecise when there are outliers or a large dynamic range, eg, t-statistic maps - this is how the problem was brought to my attention.
I experimented with using a mask of all the labels to define the histogram range for intensity voxels inside the mask. I also increased the number of histogram bins. It works better, but still, I'm not sure it's a good idea to include imprecise information, and I expect most users who really want median would rather compute it exactly with numpy or similar.
Mean, Min, Max, and …
=> Label geometry histogram

Examples/antsAI.cxx
Prevents the learning rate being carried over to new start points
Should fix (#1860) without having to bump ITK
Somewhat inefficient but doesn't appear to have a large impact on run time (about 10% longer)
=> BUG: Set scales estimator for antsAI

Examples/ImageMath.cxx, Examples/ImageMath_Templates.hxx, Tensor/itkPreservationOfPrincipalDirectionTensorReorientationImageFilter.cxx, Tensor/itkPreservationOfPrincipalDirectionTensorReorientationImageFilter.h
There was a lot of unused code in the PPD filter, and it was not consistent about how it expected the input tensors to be based - it seems it corrected for the header orientation with affine transforms, but not with displacement fields. A comment suggested this was intentional, but it produces wrong results if the resampled tensor image does not have an identity header transform. 
I've simplified the code in this PR.
Tensors should be stored in voxel orientation. In antsApplyTransforms, they are reoriented correctly into the voxel orientation of the reference space (#678).  In the new PPD filter, the tensors are rebased into physical orientation, the rotation from the transform is applied, then they are rebased onto the voxel orientation.
My motivation for getting back into this issue is …
=> BUG: Fix tensor reorientation with displacement fields

Examples/RebaseTensorImage.cxx, Examples/ReorientTensorImage.cxx, Tensor/itkPreservationOfPrincipalDirectionTensorReorientationImageFilter.cxx, Tensor/itkPreservationOfPrincipalDirectionTensorReorientationImageFilter.h, Utilities/itkantsReadWriteTransform.h
Reorienting with a composite transform removes the requirement to collapse all transforms into a single displacement field.
=> ENH: Support composite transforms in ReorientTensorImage

Examples/LabelGeometryMeasures.cxx, Examples/antsApplyTransforms.cxx, Utilities/ReadWriteData.h
We've had a default tensor pixel value for some time, but it's only used when the fixed and moving domains don't overlap. 
A bigger problem is that when the tensor volume is brain masked, the interpolation with zeros in the log space causes huge tensors at the edge of the brain, which hinders visualization of tensor glyphs or mean diffusivity images.
Currently, this can be avoided with the `TensorMask` option in `ImageMath`.
This PR allows the use of a default isotropic tensor in background voxels. In antsApplyTransforms, the default mean diffusivity specified with `-f` is now used in background voxels of the moving image, so that resampling is more sensible along the edge of the brain.
The default value of -f remains zero, so the user has to opt-in to using the new functionality.
=> Dt background value

Examples/ImageMath.cxx, Examples/ReorientTensorImage.cxx, Examples/antsApplyTransforms.cxx
Now that the PPD filter supports composite transforms, it is feasible to add it directly to antsApplyTransforms. This avoids the need to use a separate program and keep track of the transforms to use.
This simplifies things for users, and reduces potential for mistakes in transform composition.
To make this happen, I had to change the tensor type in AAT from a general itk::SymmetricSecondRankTensor to a DiffusionTensor3D. Typing this, I realize I should document this in the usage.
I think DiffusionTensor3D is the vast majority of use cases, so I'm thinking it would not be worth complicating usage by separately supporting generic tensors. Non-diffusion tensors might not also work with the log transformation that we apply automatically.
=> Apply PPD reorientation for tensor data in antsApplyTransforms

Examples/CreateJacobianDeterminantImage.cxx, Utilities/itkDeformationFieldGradientTensorImageFilter.h, Utilities/itkDeformationFieldGradientTensorImageFilter.hxx
Discussed in #1884 
I added more examples with synthetic data at
https://github.com/cookpa/antsJacobianExample
I think the Jacobian matrix as well as the determinant were not properly computed in physical space. For some cases, these errors could cancel out leading to results that appear correct.
I've simplified the ANTs Jacobian filter to behave more like the itkDisplacementFieldTransform method, which works consistently well across different image orientations.
I would really like some validation on external real data, but don't have time to pursue that for a couple of weeks at least. Opening a draft PR for feedback
=> BUG: Jacobian determinants incorrect for non-identity direction matrices

Examples/ANTSIntegrateVectorField.cxx, Examples/ANTSUseDeformationFieldToGetAffineTransform.cxx, Examples/ANTSUseLandmarkImagesToGetAffineTransform.cxx, Examples/LaplacianThickness.cxx, Examples/MeasureImageSimilarity.cxx, Examples/WarpImageMultiTransform.cxx, Examples/WarpTensorImageMultiTransform.cxx, Examples/WarpTimeSeriesImageMultiTransform.cxx, Examples/antsAI.cxx, ImageRegistration/itkANTSImageRegistrationOptimizer.cxx, ImageRegistration/itkAvantsMutualInformationRegistrationFunction.h, ImageRegistration/itkCrossCorrelationRegistrationFunction.h, ImageRegistration/itkExpectationBasedPointSetRegistrationFunction.h, ImageRegistration/itkExpectationBasedPointSetRegistrationFunction.hxx, ImageRegistration/itkProbabilisticRegistrationFunction.h, ImageRegistration/itkSpatialMutualInformationRegistrationFunction.h, ImageRegistration/itkSyNDemonsRegistrationFunction.h, ImageSegmentation/antsAtroposSegmentationImageFilter.hxx, ImageSegmentation/antsHistogramParzenWindowsListSampleFunction.hxx, ImageSegmentation/antsJointHistogramParzenShapeAndOrientationListSampleFunction.hxx, ImageSegmentation/antsListSampleFunction.h, Tensor/itkWarpTensorImageMultiTransformFilter.h, Utilities/itkLabeledPointSetFileWriter.hxx, Utilities/itkManifoldParzenWindowsPointSetFunction.h, Utilities/itkPointSetFunction.h, Utilities/itkWarpImageMultiTransformFilter.h, Utilities/itkWarpImageWAffineFilter.h, Utilities/itkWarpTensorImageMultiTransformFilter.h
For the sake of code readability, a new 'CoordinateType' alias is added for
each nested 'CoordRepType' alias. The old 'CoordRepType' aliases will still be
available with ITK 6.0, but it is recommended to use 'CoordinateType' instead.
The 'CoordRepType' aliases will be removed when 'ITK_FUTURE_LEGACY_REMOVE' is
enabled. Similarly, 'InputCoordinateType', 'OutputCoordinateType', and
'ImagePointCoordinateType' replace 'InputCoordRepType', 'OutputCoordRepType',
and 'ImagePointCoordRepType', respectively.
Used ITK/Utilities/Maintenance/migrate-itk6-code-recommendations.sh to apply updates.
=> STYLE: CoordRepType -> CoordinateType code readability

README.md
Remove spare opening parenthesis in README link.
=> DOC: Remove spare opening parenthesis in README link
