- Scripts/buildtemplateparallel.sh
So for some reason PBS qsub in buildtemplateparallel.sh uses a queue named **nopreempt**.
I guess the original author encoded a local site's policy here? Ideally the **-q** option should be **optional** in the qsub command but I did not want to break other site's setups.
> ENH: add option '-q' to override default PBS queue

- Examples/ResampleImageBySpacing.cxx
I was trying to resample a diffusion image but this function only accepts 2 or 3 dimensional images... I've added the case dimension 4. 
Example execution:
ResampleImageBySpacing 4 in.nii.gz out.nii.gz 1 1 1 1
Cheers,
Marc.
> Resample 4 dimensional image

- Examples/antsRegistrationOptimizerCommandIterationUpdate.h
- SuperBuild/External_ITKv4.cmake
This provides a working version of ANTS
for convering displacements to/from itk::Image
and itk::Transform without loss of precision.
Fixes https://github.com/stnava/ANTs/issues/74
Do not push this yet.  We need to wait for ITK to incorporate a patch.
> WIP: ITK fix for resolution bug

- SuperBuild/External_ITKv4.cmake
> Update ITK version to fix build support for MINC transforms

- Temporary/itkMeanSquaresPointSetToPointSetIntensityMetricv4.h
This addresses a compiler error in linux build.
> BUG: Type should be defined before it is used

- SuperBuild/External_ITKv4.cmake
> Add support for MINC transform format

- Utilities/itkAdaptiveNonLocalMeansDenoisingImageFilter.hxx
This patch set fixes a nasty bug where sporadic failures occurred in DenoiseImage (especially on Linux).
> Fixed initialization error

- ANTS.cmake
- Examples/CMakeLists.txt
> Revert "Vtk examples fix"

- Scripts/sliceBySliceOperation.sh
Corrected the path and added the check for direction input which must be between 0 and 2, both inclusive.
> Corrected the path of printheader and added check for direction

- SuperBuild/External_ITKv4.cmake
Fixes broken MINC with internal compression using deflate.
Changes in ITK versions:
https://github.com/InsightSoftwareConsortium/ITK/compare/2714cc1805f50504f5b9a60d0f62ffec8e73989...5aad8ac86968a12be74a31ef6493811c0ea13d05
> Update ITK version to fix broken HFD5-deflate plugin

- Scripts/antsRegistrationSpaceTime.sh
bug was introduced in 51b08bb5ab03275df81f6c7047ab7d2d59705c8a
> BF: adding trailing } for Help in antsRegistrationSpaceTime.sh

- Scripts/antsRegistrationSyN.sh
- Scripts/antsRegistrationSyNQuick.sh
Hey @stnava, I'd like to modify the available masking options in the SyN scripts.  Currently you set them up such that a single mask can be specified and it is applied to the last stage.  I'd like to open that up and allow for multiple masks to be specified.  Take a look and let me know if you think these changes are okay.
> ENH:  Modifying masking option.

- Examples/MeasureImageSimilarity.cxx
Complete refactorization of MeasureImageSimilarity to use ants command line interface and ITKv4 metrics.
> ENH:  Refactoring MeasureImageSimilarity to use ITKv4 metrics.

- Examples/antsRegistration.cxx
> ENH: Changed usage string for restrict-deformation

- SuperBuild/External_ITKv4.cmake
Changing to ITK version 4.12 - I think this is the only place necessary to change, correct?
> changing ITK version

- SuperBuild/External_ITKv4.cmake
Follow up to https://github.com/ANTsX/ANTs/pull/501 exposed when testing on Travis.
> Set VTK_DIR if not using system version

- Examples/ImageMath.cxx
Very small typo in help for STAPLE.
> Fix typo in help for STAPLE

- README.md
I hope you'll find advertising this connection of mutual benefit.
> Mention OpenNeuro in the README

- Examples/CreateTiledMosaic.cxx
- Examples/ImageMath_Templates.hxx
- Examples/SmoothDisplacementField.cxx
- Examples/ThresholdImage.cxx
- Examples/itkantsRegistrationHelper.hxx
- ImageSegmentation/antsAtroposSegmentationImageFilter.hxx
- SuperBuild/External_ITKv4.cmake
- SuperBuild/External_ITKv4.cmake.orig
- Utilities/ReadWriteData.h
- Utilities/itkAdaptiveNonLocalMeansDenoisingImageFilter.h
- Utilities/itkAverageOverDimensionImageFilter.hxx
- Utilities/itkMultiScaleLaplacianBlobDetectorImageFilter.hxx
- Utilities/itkNonLocalPatchBasedImageFilter.h
- Utilities/itkNonLocalSuperresolutionImageFilter.h
These changes were identified as failures when deprecated code from ITK is removed.
> Fix itk future deprecation errors

- Scripts/antsCorticalThickness.sh
Bug happens when the script checks if the output exists.
> BUG: fixed a bug in CorticalThickness script

- Examples/antsAI.cxx
- Examples/antsMotionCorr.cxx
- Examples/itkantsRegistrationHelper.h
via an environment variable called ANTS_RANDOM_SEED
when implemented, this should be over-ridden by values
that are passed via command line.
> ENH: allow random seed control

- SuperBuild/External_VTK_build_step.cmake.in
> Fix specification of make command to pass -j values through

- .travis.yml
Hello.
This PR is for refactoring of `.travis.yml`.
We can make `.travis.yml` more readable with YAML multi line syntax "|".
See https://stackoverflow.com/questions/38745696/how-to-use-multiline-command-in-script-with-yaml
> Make .travis.yml more readable with YAML syntax "|".

- Examples/itkTestMain.h
Update to utilize the new MultiThreaderBase needed for
setting the number of threads.
> ENH: Update for ITKv5 MultiThreader model

- Examples/ImageMath_Templates.hxx
- Examples/antsAffineInitializer.cxx
- ImageRegistration/itkANTSImageRegistrationOptimizer.h
- Temporary/antsFastMarchingImageFilter.hxx
- Utilities/antsSCCANObject.h
- Utilities/antsSCCANObject.hxx
- Utilities/itkSurfaceImageCurvature.hxx
Various compiler warnings on newer compilers.
> Fix comp warnings

- .travis.yml
Not sure if this will work, please don't merge until Travis completes
> Updating travis Linux to Xenial, which uses GCC 5

- Examples/ExtractSliceFromImage.cxx
An optional boolean argument is added to the command line. The default is 0, but if
it is set to 1 by user, the extracted slice will be saved in a blank original space.
Usage:
ExtractSliceFromImage imageDimension inputImage outputSlice direction(e.g. 0, 1, 2) slice_number [KeepSliceInOriginalSpace (0 or 1)]
> ENH: Added a new feature to ExtractSliceFromImage

- .travis.yml
Hoping this may fix the timeouts.
> Convert cmake to use ninja build system in travis for improved build performance

- ImageSegmentation/itkWeightedVotingFusionImageFilter.hxx
In WeightedVotingFusion filter, iterate through the weighted sum image only if relevant outputs are requested.
> ENH: avoid iterating through the image if not necessary

- Examples/ThresholdImage.cxx
> Fix ThresholdImage

- .travis.yml
After a bunch of googling it seems this is the proper way to force ninja to be verbose. Tested locally seems to work
Hopefully this works on Travis as well.
> Switch to verbose Ninja properly

- Examples/Atropos.cxx
- Examples/ImageMath_Templates.hxx
- Examples/antsDisplacementAndVelocityFieldRegistrationCommandIterationUpdate.h
- Examples/antsRegistrationCommandIterationUpdate.h
- Examples/antsRegistrationOptimizerCommandIterationUpdate.h
- Examples/antsUtilities.cxx
- Examples/antsUtilities.h
- ImageRegistration/itkANTSAffine3DTransform.hxx
- ImageSegmentation/antsAtroposSegmentationImageFilter.h
- ImageSegmentation/antsAtroposSegmentationImageFilter.hxx
- Tensor/TensorFunctions.h
- Utilities/antsCommandLineParser.cxx
- Utilities/antsSCCANObject.h
- Utilities/itkAverageOverDimensionImageFilter.hxx
- Utilities/itkPulsedArterialSpinLabeledCerebralBloodFlowImageFilter.hxx
- Utilities/itkSurfaceCurvatureBase.hxx
- Utilities/itkSurfaceImageCurvature.hxx
Round 1 for:
https://github.com/ANTsX/ANTs/issues/854
> COMP:  GCC 9 enhanced warnings.

- Examples/iMath.cxx
- Utilities/ReadWriteData.cxx
Rebase of #796 so its not a commit on master, and so Travis can test it.
> Fix some windows compile errors

- Examples/antsMotionCorr.cxx
Note that no support was added for either Gaussian or genericLabel
interpolation routines, as those require adapting parameters according
to the voxel dimensions. If users want these, they can always fall
back to using antsApplyTransforms for a more generic solution.
> Add support for an --interpolation flag in antsMotionCorr

- .circleci/config.yml
- Dockerfile
This PR adds an automatic Docker image build on CircleCI.
> Automatically build Docker Images

- Examples/antsUtilities.h
https://github.com/ANTsX/ANTs/issues/968
> BUG:  Address incorrect output in morphological close/open.

- CMake/ANTSExternalData.cmake
Use new girder interface for accessing data
files.
> BUG: Midas server was deprecated in 2018

- README.md
- code_of_conduct.md
Still need to specify reporting procedures.
> WIP:  Add code of conduct.

- Examples/antsSliceRegularizedRegistration.cxx
> BUG: Update transform when polynomial regularization is not used

- ImageRegistration/itkANTSImageRegistrationOptimizer.h
https://github.com/ANTsX/ANTs/issues/1076
> BUG:  Fix expansion factors.

- .circleci/config.yml
Trying again by moving the environment setting within the run block
> ENH: Set Docker container creation timezone

- Scripts/antsCorticalThickness.sh
- Scripts/antsLongitudinalCorticalThickness.sh
Various updates to bring this up to date with current usage and improve readability.
> Antsct usage

- Examples/antsApplyTransforms.cxx
- Utilities/ReadWriteData.h
Revisiting [this issue](https://github.com/ANTsX/ANTs/issues/614).  Don't think the multi-channel works.  Need to explicitly read it in as a 5-D image.   @cookpa , can you check this if you have some time?
> ENH:  Accommodate AFNI stats images.

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/build_errors.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/other_questions.md
- .github/pull_request_template.md
Just updating these and putting the instructions inside comments to make it easier for users.
> ENH: Update issue templates, add PR template

- Dockerfile
> ENH: Run short tests during build

- Examples/PrintHeader.cxx
- SuperBuild/External_ITKv5.cmake
> Update to newest ITK hash

- Utilities/tagRelease.pl
ENH: Check for existing tags before committing any changes
> BUG: Parse Release numbers > 9 properly

- Utilities/tagRelease.pl
Just fixing the versioning script for making releases
> BUG: Fix check for existing versions, other checks

- ANTS.cmake
> ENH: Install scripts for non-release configurations

- SuperBuild/External_ITKv5.cmake
The v4 metric superclass was not setting number of workers correctly.
> PERF: Bump ITK to control multi-threading in MI registration.

- Scripts/antsBrainExtraction.sh
Rearranged script so that defaults can be in the help message.
> Clarify antsBrainExtraction.sh usage

- Tensor/TensorFunctions.h
- Utilities/ReadWriteData.h
- Utilities/itkDiReCTImageFilter.hxx
Remove a couple compilation warnings discovered for an unrelated pull request.
> COMP:  Address some compilation warnings.

- Scripts/antsMultivariateTemplateConstruction.sh
- Scripts/antsMultivariateTemplateConstruction2.sh
> BUG: Fix typos

- Scripts/antsCorticalThickness.sh
> BUG: Wrong elapsed time in registration stage

- Tensor/TensorFunctions.h
Addresses https://github.com/ANTsX/ANTsPy/issues/487
> BUG:  Wrong return type.

- Examples/itkantsRegistrationHelper.hxx
Addresses https://github.com/ANTsX/ANTs/issues/1572
> BUG:  Avoid divide by 0.

- Scripts/antsAtroposN4.sh
Missed because it wasn't at the top of the script
> BUG: DenoiseImage check

- Examples/sccan.cxx
The import of random also had the if statement that stopped working on Windows
> COMP: need to import random

- Scripts/antsIntermodalityIntrasubject.sh
Looks like the syntax was wrong in the check for required programs
Fixes #1599
> BUG: check for required programs

- Scripts/antsCorticalThickness.sh
- Scripts/antsLongitudinalCorticalThickness.sh
Also allow templateflow labels (almost bids but use SCGM instead of SGM).
This lets users run ACT with a templateflow template, eg tpl-OASIS30ANTs, without first renaming the priors 01 through 06.
For backwards compatibility, and because Atropos requires it, output is still numbered 1-6.
> ENH: Allow priors to be specified with BIDS labels in ants*CorticalThickness.sh

- Tensor/TensorFunctions.h
> COMP: Avoid type conversion errors on Mac with new ITK

- CMake/CCache.cmake
- CMake/ProjectSourceVersion.cmake
> COMP: Fix some CMake warnings

- Examples/ImageMath_Templates.hxx
- Utilities/antsSCCANObject.h
- Utilities/antsSCCANObject.hxx
- Utilities/itkSurfaceCurvatureBase.hxx
- Utilities/itkSurfaceImageCurvature.hxx
Remove compilation warnings, mostly "unused variable."
> COMP:  Address warnings.

- Examples/SetOrigin.cxx
- Examples/SetSpacing.cxx
- ImageRegistration/itkExpectationBasedPointSetRegistrationFunction.hxx
- Utilities/ReadWriteData.h
- Utilities/itkWarpImageMultiTransformFilter.hxx
> COMP:  More warnings.

- Examples/itkantsRegistrationHelper.h
https://github.com/ANTsX/ANTs/issues/1668
> DOC:  MI clarification in logger.

- ImageRegistration/itkANTSImageRegistrationOptimizer.cxx
- ImageRegistration/itkANTSImageRegistrationOptimizer.h
- ImageRegistration/itkAvantsMutualInformationRegistrationFunction.cxx
- ImageRegistration/itkAvantsMutualInformationRegistrationFunction.h
- ImageRegistration/itkExpectationBasedPointSetRegistrationFunction.hxx
- ImageRegistration/itkSpatialMutualInformationRegistrationFunction.cxx
- ImageRegistration/itkSpatialMutualInformationRegistrationFunction.h
- Utilities/itkWarpImageMultiTransformFilter.hxx
> COMP:  ANTs warnings 3.

- Examples/iMathFunctions1.hxx
> BUG: iMath Truncate failed on images with negative intensities

- Examples/LesionFilling.cxx
> ENH: make lesion image uint16 to allow more than 255 lesions

- Examples/LabelOverlapMeasures.cxx
Add 4-D images for label overlap measures.
> ENH:  Add dimension 4.

- Scripts/antsMultivariateTemplateConstruction.sh
- Scripts/antsMultivariateTemplateConstruction2.sh
https://github.com/ANTsX/ANTs/issues/1731
> ENH: More than 10 modalities.

- .github/workflows/ci-docker.yml
Trying to be more consistent with versioning by using `X.Y.Z` not `vX.Y.Z`
> CI: Docker tags

- .github/workflows/release-binaries.yml
Add 24.04 by copy-paste of the existing GH action.
> ENH: Add Ubuntu 24.04

- CITATION.cff
Github can include a sidebar link if you give it this file. I put the ANTsX ecosystem paper as the main citation but ask users to check the README for relevant methods papers.
> DOC: Create CITATION.cff

- .github/workflows/ci-docker.yml
> BUG: Fix release tags

- .github/workflows/ci-docker.yml
> BUG: fixing tags again

- Scripts/antsMultivariateTemplateConstruction2.sh
Unbound variables prevented usage printing
> BUG: Fix script usage

- .github/workflows/release-docker-binaries.yml
Name the release binaries properly
> CI: Fix artifact names

- Examples/antsTransformInfo.cxx
Check if cast to matrix transform works
> ENH: Enhanced error checking

- README.md
> DOC: Link to conda forge

- Examples/ConvertScalarImageToRGB.cxx
ConvertScalarImageToRGB usage update
> DOC: Better usage

- Examples/LabelGeometryMeasures.cxx
Bad form on my part, should be fixed now
> ENH: Remove static output stream that was causing problems with ANTsPy

- SuperBuild/External_ITKv5.cmake
> ENH: Update itk release

- Scripts/antsMultivariateTemplateConstruction2.sh
> BUG: Backup templates tried to copy non-existent files

- Examples/antsApplyTransforms.cxx
> BUG: Need to compute Exp(D) before reorienting

- Utilities/ReadWriteData.h
ANTsPy does not support a tensor pixel type, the code was causing segmentation faults. 
Updated to read/write tensor data from/to a pointer as a vector image.
> ENH: Fix tensor I/O for python

- Examples/antsTransformInfo.cxx
> ENH: allow antsTransformInfo to read MatrixOffsetTransformBase

- Examples/PrintHeader.cxx
Print matrices and vectors, remove redundant info
Fixes #960
> ENH: Fix header printing
